apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: monitoring
  name: monitoring
spec:
  replicas: 1
  selector:
      matchLabels:
          name: monitoring
  template:
    metadata:
      creationTimestamp: null
      labels:
              #io.kompose.service: iam
        name: monitoring
    spec:
      containers:
      - image: 10.81.1.50:5000/monitoring:7
        name: monitoring
        ports:
        - containerPort: 8800
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "8800"
        - name: PROTOCOL
          value: http
        - name: MONASCA_IP
          value: "monasca-ip:8070"  
        - name: MIDDLEWARE_IP
          value: http://middleware:8001
        - name: IAM_IP
          value: http://iam:8003
        - name: MONASCA_CPU_TIME
          value: 50,seconds
        - name: MONASCA_RAM_TIME
          value: 6.5,days
        - name: MONASCA_NETWORK_DOWN_TIME
          value: 6,minutes
        - name: MONASCA_NETWORK_UP_TIME
          value: 6,minutes
        - name: MONASCA_STORAGE_TIME
          value: 50,seconds  
    #ms-logger serice
        - name: MS_LOGGER_IP
          value: ms-logger
        - name: MS_LOGGER_PORT
          value: "8012"
        - name: MS_LOGGER_SECRET_KEY
          value: BC2B36B81AB89F3B83AD227DCAD56
        - name: MS_LOGGER_THIS_SERVICE_NAME
          value: monitoring
        - name: MS_LOGGER_THIS_SERVICE_IP
          value: monitoring
        - name: MS_LOGGER_THIS_SERVICE_PORT
          value: "8800"
        - name: LOG_TARGET
          value: both
        
      #restartPolicy: Always
  strategy:
     type: RollingUpdate
     rollingUpdate:
       maxUnavailable: 0
       maxSurge: 1
